---
apiVersion: jetstream.nats.io/v1beta1
kind: StreamTemplate
metadata:
  name: mystreamtemplate
spec:
  servers:
  - nats://localhost:4222
  credentialsSecret:
    name: myncreds
    key: nats-myusr
  name: mystreamtemplate
  maxStreams: 2
  subjects: ["orders.*"]
  storage: memory
  maxAge: 1h
