---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.17.2
  name: streamtemplates.jetstream.nats.io
spec:
  group: jetstream.nats.io
  names:
    kind: StreamTemplate
    listKind: StreamTemplateList
    plural: streamtemplates
    singular: streamtemplate
  scope: Namespaced
  versions:
  - name: v1beta1
    schema:
      openAPIV3Schema:
        description: StreamTemplate is a specification for a StreamTemplate resource
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: StreamTemplateSpec is the spec for a StreamTemplate resource
            properties:
              allowMsgTtl:
                type: boolean
              description:
                type: string
              discard:
                type: string
              duplicateWindow:
                type: string
              maxAge:
                type: string
              maxBytes:
                type: integer
              maxConsumers:
                type: integer
              maxMsgSize:
                type: integer
              maxMsgs:
                type: integer
              maxMsgsPerSubject:
                type: integer
              maxStreams:
                type: integer
              mirror:
                properties:
                  externalApiPrefix:
                    type: string
                  externalDeliverPrefix:
                    type: string
                  filterSubject:
                    type: string
                  name:
                    type: string
                  optStartSeq:
                    type: integer
                  optStartTime:
                    type: string
                required:
                - externalApiPrefix
                - externalDeliverPrefix
                - filterSubject
                - name
                - optStartSeq
                - optStartTime
                type: object
              name:
                type: string
              noAck:
                type: boolean
              placement:
                properties:
                  cluster:
                    type: string
                  tags:
                    items:
                      type: string
                    type: array
                required:
                - cluster
                - tags
                type: object
              replicas:
                type: integer
              retention:
                type: string
              sources:
                items:
                  properties:
                    externalApiPrefix:
                      type: string
                    externalDeliverPrefix:
                      type: string
                    filterSubject:
                      type: string
                    name:
                      type: string
                    optStartSeq:
                      type: integer
                    optStartTime:
                      type: string
                  required:
                  - externalApiPrefix
                  - externalDeliverPrefix
                  - filterSubject
                  - name
                  - optStartSeq
                  - optStartTime
                  type: object
                type: array
              storage:
                type: string
              subjectDeleteMarkerTtl:
                type: string
              subjects:
                items:
                  type: string
                type: array
            required:
            - allowMsgTtl
            - description
            - discard
            - duplicateWindow
            - maxAge
            - maxBytes
            - maxConsumers
            - maxMsgSize
            - maxMsgs
            - maxMsgsPerSubject
            - maxStreams
            - mirror
            - name
            - noAck
            - placement
            - replicas
            - retention
            - sources
            - storage
            - subjectDeleteMarkerTtl
            - subjects
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      type: string
                    message:
                      type: string
                    reason:
                      type: string
                    status:
                      type: string
                    type:
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
              observedGeneration:
                format: int64
                type: integer
            required:
            - conditions
            - observedGeneration
            type: object
        required:
        - spec
        - status
        type: object
    served: true
    storage: true
