---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.17.2
  name: keyvalues.jetstream.nats.io
spec:
  group: jetstream.nats.io
  names:
    kind: KeyValue
    listKind: KeyValueList
    plural: keyvalues
    singular: keyvalue
  scope: Namespaced
  versions:
  - name: v1beta2
    schema:
      openAPIV3Schema:
        description: Stream is a specification for a Stream resource
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: StreamSpec is the spec for a Stream resource
            properties:
              baseStreamConfig:
                properties:
                  connectionOpts:
                    properties:
                      account:
                        type: string
                      creds:
                        type: string
                      jsDomain:
                        type: string
                      nkey:
                        type: string
                      servers:
                        items:
                          type: string
                        type: array
                      tls:
                        properties:
                          clientCert:
                            type: string
                          clientKey:
                            type: string
                          rootCas:
                            items:
                              type: string
                            type: array
                        required:
                        - clientCert
                        - clientKey
                        - rootCas
                        type: object
                      tlsFirst:
                        type: boolean
                    required:
                    - account
                    - creds
                    - jsDomain
                    - nkey
                    - servers
                    - tls
                    - tlsFirst
                    type: object
                  preventDelete:
                    type: boolean
                  preventUpdate:
                    type: boolean
                required:
                - connectionOpts
                type: object
              bucket:
                type: string
              compression:
                type: boolean
              description:
                type: string
              history:
                type: integer
              limitMarkerTtl:
                description: LimitMarkerTTL is how long the bucket keeps markers when
                  keys are removed by the TTL setting, 0 meaning markers are not supported
                format: int64
                type: integer
              maxBytes:
                type: integer
              maxValueSize:
                type: integer
              mirror:
                properties:
                  externalApiPrefix:
                    type: string
                  externalDeliverPrefix:
                    type: string
                  filterSubject:
                    type: string
                  name:
                    type: string
                  optStartSeq:
                    type: integer
                  optStartTime:
                    type: string
                  subjectTransforms:
                    items:
                      properties:
                        dest:
                          type: string
                        source:
                          type: string
                      required:
                      - dest
                      - source
                      type: object
                    type: array
                required:
                - externalApiPrefix
                - externalDeliverPrefix
                - filterSubject
                - name
                - optStartSeq
                - optStartTime
                - subjectTransforms
                type: object
              placement:
                properties:
                  cluster:
                    type: string
                  tags:
                    items:
                      type: string
                    type: array
                required:
                - cluster
                - tags
                type: object
              replicas:
                type: integer
              republish:
                properties:
                  destination:
                    type: string
                  headers_only:
                    type: boolean
                  source:
                    type: string
                required:
                - destination
                - source
                type: object
              sources:
                items:
                  properties:
                    externalApiPrefix:
                      type: string
                    externalDeliverPrefix:
                      type: string
                    filterSubject:
                      type: string
                    name:
                      type: string
                    optStartSeq:
                      type: integer
                    optStartTime:
                      type: string
                    subjectTransforms:
                      items:
                        properties:
                          dest:
                            type: string
                          source:
                            type: string
                        required:
                        - dest
                        - source
                        type: object
                      type: array
                  required:
                  - externalApiPrefix
                  - externalDeliverPrefix
                  - filterSubject
                  - name
                  - optStartSeq
                  - optStartTime
                  - subjectTransforms
                  type: object
                type: array
              storage:
                type: string
              ttl:
                type: string
            required:
            - baseStreamConfig
            - bucket
            - compression
            - description
            - history
            - maxBytes
            - maxValueSize
            - mirror
            - placement
            - replicas
            - republish
            - sources
            - storage
            - ttl
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      type: string
                    message:
                      type: string
                    reason:
                      type: string
                    status:
                      type: string
                    type:
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
              observedGeneration:
                format: int64
                type: integer
            required:
            - conditions
            - observedGeneration
            type: object
        required:
        - spec
        - status
        type: object
    served: true
    storage: true
