---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.17.2
  name: streams.jetstream.nats.io
spec:
  group: jetstream.nats.io
  names:
    kind: Stream
    listKind: StreamList
    plural: streams
    singular: stream
  scope: Namespaced
  versions:
  - name: v1beta1
    schema:
      openAPIV3Schema:
        description: Stream is a specification for a Stream resource
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: StreamSpec is the spec for a Stream resource
            properties:
              allowMsgTtl:
                type: boolean
              description:
                type: string
              discard:
                type: string
              duplicateWindow:
                type: string
              maxAge:
                type: string
              maxBytes:
                type: integer
              maxConsumers:
                type: integer
              maxMsgSize:
                type: integer
              maxMsgs:
                type: integer
              maxMsgsPerSubject:
                type: integer
              mirror:
                properties:
                  externalApiPrefix:
                    type: string
                  externalDeliverPrefix:
                    type: string
                  filterSubject:
                    type: string
                  name:
                    type: string
                  optStartSeq:
                    type: integer
                  optStartTime:
                    type: string
                required:
                - externalApiPrefix
                - externalDeliverPrefix
                - filterSubject
                - name
                - optStartSeq
                - optStartTime
                type: object
              name:
                type: string
              noAck:
                type: boolean
              placement:
                properties:
                  cluster:
                    type: string
                  tags:
                    items:
                      type: string
                    type: array
                required:
                - cluster
                - tags
                type: object
              replicas:
                type: integer
              retention:
                type: string
              sources:
                items:
                  properties:
                    externalApiPrefix:
                      type: string
                    externalDeliverPrefix:
                      type: string
                    filterSubject:
                      type: string
                    name:
                      type: string
                    optStartSeq:
                      type: integer
                    optStartTime:
                      type: string
                  required:
                  - externalApiPrefix
                  - externalDeliverPrefix
                  - filterSubject
                  - name
                  - optStartSeq
                  - optStartTime
                  type: object
                type: array
              storage:
                type: string
              subjectDeleteMarkerTtl:
                type: string
              subjects:
                items:
                  type: string
                type: array
            required:
            - allowMsgTtl
            - description
            - discard
            - duplicateWindow
            - maxAge
            - maxBytes
            - maxConsumers
            - maxMsgSize
            - maxMsgs
            - maxMsgsPerSubject
            - mirror
            - name
            - noAck
            - placement
            - replicas
            - retention
            - sources
            - storage
            - subjectDeleteMarkerTtl
            - subjects
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      type: string
                    message:
                      type: string
                    reason:
                      type: string
                    status:
                      type: string
                    type:
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
              observedGeneration:
                format: int64
                type: integer
            required:
            - conditions
            - observedGeneration
            type: object
        required:
        - spec
        - status
        type: object
    served: true
    storage: false
  - name: v1beta2
    schema:
      openAPIV3Schema:
        description: Stream is a specification for a Stream resource
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: StreamSpec is the spec for a Stream resource
            properties:
              allowAtomicPublish:
                type: boolean
              allowDirect:
                type: boolean
              allowMsgCounter:
                type: boolean
              allowMsgSchedules:
                type: boolean
              allowMsgTtl:
                type: boolean
              allowRollup:
                type: boolean
              baseStreamConfig:
                properties:
                  connectionOpts:
                    properties:
                      account:
                        type: string
                      creds:
                        type: string
                      jsDomain:
                        type: string
                      nkey:
                        type: string
                      servers:
                        items:
                          type: string
                        type: array
                      tls:
                        properties:
                          clientCert:
                            type: string
                          clientKey:
                            type: string
                          rootCas:
                            items:
                              type: string
                            type: array
                        required:
                        - clientCert
                        - clientKey
                        - rootCas
                        type: object
                      tlsFirst:
                        type: boolean
                    required:
                    - account
                    - creds
                    - jsDomain
                    - nkey
                    - servers
                    - tls
                    - tlsFirst
                    type: object
                  preventDelete:
                    type: boolean
                  preventUpdate:
                    type: boolean
                required:
                - connectionOpts
                type: object
              compression:
                type: string
              consumerLimits:
                properties:
                  inactiveThreshold:
                    type: string
                  maxAckPending:
                    type: integer
                required:
                - inactiveThreshold
                - maxAckPending
                type: object
              denyDelete:
                type: boolean
              denyPurge:
                type: boolean
              description:
                type: string
              discard:
                type: string
              discardPerSubject:
                type: boolean
              duplicateWindow:
                type: string
              firstSequence:
                format: int64
                type: integer
              maxAge:
                type: string
              maxBytes:
                type: integer
              maxConsumers:
                type: integer
              maxMsgSize:
                type: integer
              maxMsgs:
                type: integer
              maxMsgsPerSubject:
                type: integer
              metadata:
                additionalProperties:
                  type: string
                type: object
              mirror:
                properties:
                  externalApiPrefix:
                    type: string
                  externalDeliverPrefix:
                    type: string
                  filterSubject:
                    type: string
                  name:
                    type: string
                  optStartSeq:
                    type: integer
                  optStartTime:
                    type: string
                  subjectTransforms:
                    items:
                      properties:
                        dest:
                          type: string
                        source:
                          type: string
                      required:
                      - dest
                      - source
                      type: object
                    type: array
                required:
                - externalApiPrefix
                - externalDeliverPrefix
                - filterSubject
                - name
                - optStartSeq
                - optStartTime
                - subjectTransforms
                type: object
              mirrorDirect:
                type: boolean
              name:
                type: string
              noAck:
                type: boolean
              persistMode:
                type: string
              placement:
                properties:
                  cluster:
                    type: string
                  tags:
                    items:
                      type: string
                    type: array
                required:
                - cluster
                - tags
                type: object
              replicas:
                type: integer
              republish:
                properties:
                  destination:
                    type: string
                  headers_only:
                    type: boolean
                  source:
                    type: string
                required:
                - destination
                - source
                type: object
              retention:
                type: string
              sealed:
                type: boolean
              sources:
                items:
                  properties:
                    externalApiPrefix:
                      type: string
                    externalDeliverPrefix:
                      type: string
                    filterSubject:
                      type: string
                    name:
                      type: string
                    optStartSeq:
                      type: integer
                    optStartTime:
                      type: string
                    subjectTransforms:
                      items:
                        properties:
                          dest:
                            type: string
                          source:
                            type: string
                        required:
                        - dest
                        - source
                        type: object
                      type: array
                  required:
                  - externalApiPrefix
                  - externalDeliverPrefix
                  - filterSubject
                  - name
                  - optStartSeq
                  - optStartTime
                  - subjectTransforms
                  type: object
                type: array
              storage:
                type: string
              subjectDeleteMarkerTtl:
                type: string
              subjectTransform:
                properties:
                  dest:
                    type: string
                  source:
                    type: string
                required:
                - dest
                - source
                type: object
              subjects:
                items:
                  type: string
                type: array
            required:
            - allowAtomicPublish
            - allowDirect
            - allowMsgCounter
            - allowMsgSchedules
            - allowMsgTtl
            - allowRollup
            - baseStreamConfig
            - compression
            - consumerLimits
            - denyDelete
            - denyPurge
            - description
            - discard
            - discardPerSubject
            - duplicateWindow
            - firstSequence
            - maxAge
            - maxBytes
            - maxConsumers
            - maxMsgSize
            - maxMsgs
            - maxMsgsPerSubject
            - metadata
            - mirror
            - mirrorDirect
            - name
            - noAck
            - persistMode
            - placement
            - replicas
            - republish
            - retention
            - sealed
            - sources
            - storage
            - subjectDeleteMarkerTtl
            - subjectTransform
            - subjects
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      type: string
                    message:
                      type: string
                    reason:
                      type: string
                    status:
                      type: string
                    type:
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
              observedGeneration:
                format: int64
                type: integer
            required:
            - conditions
            - observedGeneration
            type: object
        required:
        - metadata
        - spec
        - status
        type: object
    served: true
    storage: true
